### ISSUE TITLE
Chart keeps on growing in height in Safari browser

### ISSUE THREAD

**Issue by jnr101** [matthewlilley/sushiswap-analytics#5]
When a pair or token page is opened in the Safari browser on Macbook, the chart provided on the page keeps growing in height.

See e.g. [https://sushiswap-analytics.vercel.app/tokens/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2](https://sushiswap-analytics.vercel.app/tokens/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2)

**Comment by matthewlilley** [comment]
@jnr101 Thanks. I'm not particularly well versed in OSX and Safari and don't have anything to test against. I'll keep the issue open for now, but I have some big UI changes incoming which I expect would solve this issue.
